steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/citric-period-368918/gcp_nodejs_project1:$COMMIT_SHA",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "gcr.io/citric-period-368918/gcp_nodejs_project1:$COMMIT_SHA"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "gcp_nodejs_project1",
        "--image=gcr.io/citric-period-368918/gcp_nodejs_project1:$COMMIT_SHA",
        "--region=europe-west1",
      ]
